version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build-dreamcast-gcc9:
    docker:
    - image: einsteinx2/dcdev-kos-toolchain:gcc-9
    working_directory: /src
    steps:
    - checkout
    - run: 
        name: Init Git Submodules
        command: .ci/bash/ci_init_submodules.sh
    - run: 
        name: Build Project
        command: .ci/bash/ci_build_dc.sh

  build-dreamcast-gcc4:
    docker:
    - image: einsteinx2/dcdev-kos-toolchain:gcc-4
    working_directory: /src
    steps:
    - checkout
    - run: 
        name: Init Git Submodules
        command: .ci/bash/ci_init_submodules.sh
    - run: 
        name: Build Project
        command: .ci/bash/ci_build_dc.sh

  build-linux-gcc9:
    docker:
    - image: gcc:9
    working_directory: /src
    steps:
    - checkout
    - run: 
        name: Init Git Submodules
        command: .ci/bash/ci_init_submodules.sh
    - run: 
        name: Install Dependencies
        command: .ci/bash/ci_install_ubuntu_deps.sh
    - run: 
        name: Build Project
        command: .ci/bash/ci_build_pc.sh

  build-windows-msvc:
    executor: win/default
    steps:
    - checkout
    - run: 
        name: Init Git Submodules
        command: .ci\powershell\ci_init_submodules.ps1
    - run:
        name: Install CMake
        command: .ci\powershell\ci_install_cmake.ps1
    - run:
        name: Build Project
        command: .ci\powershell\ci_build_pc.ps1

workflows:
  version: 2
  untagged-build:
    jobs:
    - build-dreamcast-gcc9
    - build-dreamcast-gcc4
    - build-linux-gcc9
    - build-windows-msvc
